### ISSUE TITLE
[Code Style] - Remove conosole.log

### ISSUE THREAD

**Issue by Luke9389** [TellemBigAlsentya/local-storage-favorites#7]
This one is real fast. I left a console.log in my PR and we merged it. 

Let's take it out. 

https://github.com/TellemBigAlsentya/local-storage-favorites/blob/8d48115ede34b93bb94d3e0d2838186582c078a2/app.js#L97

**Comment by alexhoffman-dev** [comment]
done

**Comment by Luke9389** [comment]
Oh, did you make a PR for this one or just push the change on the main branch?

**Comment by alexhoffman-dev** [comment]
I just pushed the changes since it was 1 line of code with no functional changes. I can set up a PR in the future for more substantive changes.

**Comment by Luke9389** [comment]
Please do! As a policy it's best to never push on `main`.
